In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from pandas.plotting import scatter_matrix
from itertools import combinations
from sklearn.model_selection import cross_val_score
%matplotlib inline

In [64]:
df = pd.read_csv('loan.csv')
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2499 entries, 6 to 2497
Data columns (total 5 columns):
Interest.Rate     2499 non-null float64
FICO.Score        2499 non-null int64
Loan.Length       2499 non-null int64
Monthly.Income    2499 non-null float64
Loan.Amount       2499 non-null int64
dtypes: float64(2), int64(3)
memory usage: 117.1 KB


In [65]:
df['approved'] = df['Interest.Rate'] <= 12
df.head()

Interest.Rate  FICO.Score  Loan.Length  Monthly.Income  Loan.Amount  \
6           15.31         670           36         4891.67         6000   
11          19.72         670           36         3575.00         2000   
12          14.27         665           36         4250.00        10625   
13          21.67         670           60        14166.67        28000   
21          21.98         665           36         6666.67        22000   

    approved  
6      False  
11     False  
12     False  
13     False  
21     False

In [66]:
y = df.approved
rows = []
for i in range(1,5):
    combos = list(combinations(['FICO.Score', 'Loan.Length', 'Monthly.Income', 'Loan.Amount'],i))
    for combo in combos:
        model = LogisticRegression(fit_intercept=True)
        accuracy = cross_val_score(model, df[list(combo)], df.approved, cv=10, scoring='accuracy').mean()
        rows.append({'Accuracy': accuracy, 'Columns': combo})
df1 = pd.DataFrame(rows)

In [67]:
df1.head()

Accuracy                    Columns
0  0.765154              (FICO.Score,)
1  0.603441             (Loan.Length,)
2  0.603040          (Monthly.Income,)
3  0.603441             (Loan.Amount,)
4  0.837152  (FICO.Score, Loan.Length)

In [68]:
m1 = LogisticRegression().fit(df[['FICO.Score']], df.approved)

In [69]:
m1.coef_

array([[ 0.02417872]])

In [70]:
m1.intercept_

array([-17.48849485])

In [82]:
m1.predict([[725]])

array([ True], dtype=bool)

In [84]:
y = df.approved
X = df[['FICO.Score']]

In [85]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [86]:
y_hat = m1.predict(X_test)

In [87]:
confusion_matrix(y_test, y_hat)

array([[473,  37],
       [121, 194]])

In [90]:
m1.score(X_test, y_test)

0.80848484848484847